### ISSUE TITLE
Frequency indication not updating if selected through other apps

### ISSUE THREAD

**Issue by vu2cpl** [K3TZR/xSDR6000#4]
I am using xsdr6k with xCAT and xDAX and logging software is rumlogNG. while running WSJTX, if i select band from dropdown menu in WSJTX, the radio switches band, the display on rumlogNG as well as pan adapter shows correct band, but the label shows old band. this display gets updated the moment you try to tune even 1 Hz or if nothing is done, after a very long time. I am attaching a screenshot. You can see active frequency is 7074, but label shows 50.313 Mhz
 
![Screenshot 2020-06-08 at 2 23 38 PM](https://user-images.githubusercontent.com/66413959/84011397-aa429b80-a993-11ea-950e-15a632cf7bbb.png)

**Comment by K3TZR** [comment]
Thank you for the report. It sounds like the display is not being redrawn when the external band change occurs. I’ll add it to my list of bugs to fix for the next version.

73’s Doug

**Comment by vu2cpl** [comment]
Thank you Doug 

73

Manoj VU2CPL

**Comment by vu2cpl** [comment]
Thank you Doug for the detailed message. I am happy you could get to the bottom of this issue. 

Will wait for the fix. 

73

Manoj VU2CPL

**Comment by K3TZR** [comment]
Manoj,

Actually, I’m still working on this and I think my explanation was premature. It’s more complicated than I thought and I think it’s my issue not the Flex protocol.

I’ll update you once I fix this.

73’s 
Doug - K3TZR

**Comment by vu2cpl** [comment]
Ok Doug, 

I am using it as it is and can wait for the fix when it’s available. 

Thank you for your hard work!

73

Manoj VU2CPL

**Comment by K3TZR** [comment]
Manoj,

The current release (v1.2.4) should fix the issue you reported. Please let me know if it does not.

73’s 
Doug - K3TZR

**Comment by vu2cpl** [comment]
Thank you Doug. Will check and revert. 
73,
Manoj VU2CPL

**Comment by vu2cpl** [comment]
Thanks Doug, its fixed with 1.24.

73

Manoj VU2CPL
