### ISSUE TITLE
Unable to move sliders on DSP panel

### ISSUE THREAD

**Issue by ofadam** [K3TZR/xSDR6000#8]
On the DSP panel, attempting to move the sliders for things like WNB, NR, etc results in the whole waterfall sliding horizontally instead of just the slider. I'm on macOS 11.2.1 and the latest version of xSDR6000.

**Comment by K3TZR** [comment]
Adam,

Thanks for the feedback. I don’t know what to say about the waterfall, it looks normal on my Mac. Could you send me a copy of the system report that shows the Displays information for your Mac. Maybe I am doing something in the waterfall (implemented in Metal) which doesn’t work on some configurations.

I’ll take a look at the DSP tab behavior.

73’s Doug

**Comment by ofadam** [comment]
Thanks, Doug! I put the display details with that issue ticket – let me know if you need anything else for either. And thanks again for creating this app and sharing it with all.

**Comment by ofadam** [comment]
This has been fixed with 1.2.14 – thank you!
